/*eslint-disable */

export const usersList = [
  {
    id: 1,
    fullName: 'Vyacheslav Litvinenko',
    shortName: 'Vyacheslav',
    username: 'tiltvinenko',
    online: true,
    imageUrl: 'https://sun9-70.userapi.com/impf/c851428/v851428511/dc9c/X5rqZO2l3Q8.jpg?size=604x603&quality=96&sign=aac8875eedd13eee3d5d805641d0dc8c&type=album'
  },
  {
    id: 2,
    fullName: 'Sonya Korotkova',
    shortName: 'Sonya',
    username: 'sooooonya',
    online: true,
    imageUrl: 'https://sun9-43.userapi.com/impf/c851428/v851428511/dcef/po3GAAjA4Yc.jpg?size=604x604&quality=96&sign=b149f9aa34c8e84d7752938c48d4a012&type=album'
  },
  {
    id: 3,
    fullName: 'Alexandr Lyakishev',
    shortName: 'Alexandr',
    username: 'naruto',
    online: true,
    imageUrl: 'https://sun9-55.userapi.com/impf/c851428/v851428511/dcad/nzCHOSymubI.jpg?size=604x604&quality=96&sign=43485fed20675ee11638189635eaafd4&type=album'
  },
  {
    id: 4,
    fullName: 'Zamir Ramazanov',
    shortName: 'Zamir',
    username: 'htoya',
    online: false,
    imageUrl: 'https://sun9-56.userapi.com/impf/c845017/v845017302/f6a61/ZgBk9vvzdeI.jpg?size=604x604&quality=96&sign=ff5aa03402bd6c0dcf447dd9f2449426&type=album'
  },
  {
    id: 5,
    fullName: 'Ilvir Harisov',
    shortName: 'Ilvir',
    username: 'kingsneverdie',
    online: false,
    imageUrl: 'https://sun9-82.userapi.com/impf/c851428/v851428511/dccb/RRBs7avCEw0.jpg?size=604x604&quality=96&sign=4a3ade3b18c97b3fc0faf7cb999eeebb&type=album'
  },
  {
    id: 6,
    fullName: 'Toha Larinov',
    shortName: 'Toha',
    username: 'burunov',
    online: false,
    imageUrl: 'https://sun9-57.userapi.com/impf/c851428/v851428511/dcb7/LhfeUh9E2q8.jpg?size=604x604&quality=96&sign=9b6bcb888f603613968386e9641683f3&type=album'
  },
];

export const testGroupMessages = [
  {
    id: null,
    senderId: 5,
    content: 'Adipisicing nulla',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 1,
    content: 'Et nulla tempor nulla',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 2,
    content: 'Veniam esse non occaecat eiusmod. Adipisicing quis consectetur irure nostrud proident.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 3,
    content: '???',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 3,
    content: 'Ut ut esse occaecat Lorem.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 3,
    content: 'Ut ut esse occaecat Lorem Boom blabla hey',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 5,
    content: 'Aute nostrud eu aliqua reprehenderit consequat fugiat nulla reprehenderit pariatur ad veniam tempor mollit irure. Tempor Lorem sint non fugiat esse duis pariatur tempor irure.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 1,
    content: 'Proident sunt cupidatat culpa id Lorem.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 6,
    content: 'Sint quis aliqua coptate tempor consequat veniam ad adipisicing aliquip.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 2,
    content: 'Anim ad proident cillum',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 6,
    content: 'Nostrud ipsum qui excepteur cupidatat proident sit exercitation mollit ad magna. Irure sit do cillum sunt nostrud dolor.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 6,
    content: 'Voluptate amet labore est eu labore.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 2,
    content: 'Nulla est labore in sint excepteur. Elit aliqua laborum dolore do.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 5,
    content: 'Nostrud occaecat pariatur laborum aliqua ad reprehenderit mollit magna ex incididunt non sunt. Ullamco sunt nulla aliqua quis ex ullamco minim.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 6,
    content: 'Cupidatat occaecat.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 1,
    content: 'Exercitation consequat amet ut nisi. Do ex enim ullamco ex ex est et aliqua laborum ullamco magna.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 2,
    content: 'Sunt amet deserunt sint amet.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 2,
    content: 'Anim reprehenderit voluptate',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 6,
    content: 'Dolor adipisicing laborum esse incididunt esse consequat cupidatat esse. Est consequat incididunt pariatur sint sint magna.',
    timestamp: '',
    attachments: [],
    isRead: true,
  },
  {
    id: null,
    senderId: 5,
    content: 'Adipisicing nulla ad ad nostrud mollit culpa ea cillum aute excepteurt.',
    timestamp: '',
    attachments: [],
    isRead: true,
  }
];

export const shortChannels = [
  {
    id: 0,
    title: 'blabla public channel 1',
    private: false,
    unreadMessagesCount: 1,
  },
  {
    id: 1,
    title: 'ura public channel 2',
    private: false,
    unreadMessagesCount: 0,
  },
  {
    id: 2,
    title: 'public 3',
    private: false,
    unreadMessagesCount: 8,
  },
  {
    id: 3,
    title: 'test channel 4',
    private: false,
    unreadMessagesCount: 0,
  },
  {
    id: 4,
    title: 'private channel 5',
    private: true,
    unreadMessagesCount: 0,
  },
  {
    id: 5,
    title: 'private channel 6',
    private: true,
    unreadMessagesCount: 0,
  },
  {
    id: 6,
    title: 'locked 7',
    private: true,
    unreadMessagesCount: 14,
  },
];

export const channels = [
  {
    id: 0,
    title: 'blabla public channel 1',
    private: false,
    videorooms: [],
    members: [1, 2, 3],
  },
  {
    id: 1,
    title: 'ura public channel 2',
    private: false,
    videorooms: [],
    members: [1, 3, 5],
  },
  {
    id: 2,
    title: 'public 3',
    private: false,
    videorooms: [],
    members: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 3,
    title: 'test channel 4',
    private: false,
    videorooms: [],
    members: [1, 3, 4],
  },
  {
    id: 4,
    title: 'private channel 5',
    private: true,
    videorooms: [],
    members: [1, 2, 3],
  },
  {
    id: 5,
    title: 'private channel 6',
    private: true,
    videorooms: [],
    members: [1, 5, 6,],
  },
  {
    id: 6,
    title: 'locked 7',
    private: true,
    videorooms: [],
    members: [1, 4, 5],
  },
];
